### ISSUE TITLE
Desenvolver o Modelo de Design dos casos de uso

### ISSUE THREAD

**Issue by erickolisveira** [marcosdosea/GestaoAnimal#62]
- [x] UC - Manter Agendamento Medicamento
- [x] UC - Manter Animais
- [x] UC - Manter Organização
- [x] UC - Manter Aplicação Medicamento

**Comment by valeriabarbosasi** [comment]
- [x] Manter Exame
- [x] Manter Consulta
- [x] Manter Responsável
- [x] Manter Cadastro Vacina

**Comment by GCaio7** [comment]
- [x] UC - Manter Lote de Animais
- [x] UC - Manter Cadastro de Medicamento
